config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
  post "/home/import", to: "home#import"
  post "/home/classify", to: "home#classify"

  match 'download', to: 'home#download', as: 'download', via: :get
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'smarter_csv'
require 'classifier-reborn'
require 'net/http'
class HomeController < ApplicationController
  def index
    @errors = ""
    @categories = ""
    @news = session[:news] || ""
    if session[:come_from_import] === 1
      @errors = session[:error]
      @categories = session[:categories]
      @class_text = session[:class_text]
    else
      session[:error] = ""
      session[:class_text] = ""
      session[:categories] = ""
      session[:class_text] = ""
    end
    session[:come_from_import] = 0
  end


  def download
    send_file 'app/assets/docs/arquivo.csv', type: 'text/csv', status: 202
  end

  def import
    array = []
    begin
      file = SmarterCSV.process(params[:file],{:chunk_size => 2})
      file.each do |row|
        array.push(row[0][:category])
      end
      arry_uniq = array.compact.uniq
      if arry_uniq.empty?
        generate_error("Seu arquivo não tem as colunas feitas corretamente, por favor reveja")
      else
        clear_msg
        training_model(file, arry_uniq)
        session[:categories] = arry_uniq
        session[:news] = get_news
      end
      session[:come_from_import] = 1
      redirect_to root_path
    rescue
      generate_error("Ouve erro em carregar o seu csv, por favor, tente novamente")
      session[:come_from_import] = 1
      redirect_to root_path
    end
  end

  def classify
    input = params[:text]
    classification = ""
    if !input.empty?
      classification = @@classifier.classify input
      session[:class_text] = "Seu Texto foi classificado como " + classification
    else
      generate_error("Você precisa colocar um texto para ser classificado")
    end
    session[:come_from_import] = 1
    redirect_to root_path
  end

  private
  def generate_error(msg)
    session[:error]= msg
  end

  def clear_msg
    session[:error]=""
  end

  def get_news
    begin
      uri = URI("https://inshortsapi.vercel.app/news?category=all")
      response=Net::HTTP.get(uri)
      data = JSON.parse response
      return data['data'][5]["content"]
    rescue
      return "Infelizmente estamos sem noticias"
    end
  end

  def training_model(file, categories)
    begin
      @@classifier = ClassifierReborn::Bayes.new categories
      file.each do |row|
        @@classifier.train row[0][:category], row[0][:text]
      end
    rescue
      generate_error("Houve um erro no treinamento do modelo")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container">
  <br>
  <h4 class="text-center">Rails Machine</h4>
  <%= image_tag("logo.png", size: "300x150", class: "rounded mx-auto d-block") %>

  <p>   Esse pequena aplicação feita com os conceitos de machine learning,
  consegue classificar sozinha qual seria o tema de algum texto adicionado.
  </p>


  <% if !@errors.nil? && @errors.length > 1 %>
  <div class="alert alert-danger" role="alert">
    <%= @errors %>
  </div>
  <% end %>


  <h6>Bem vamos a prática</h6>
  <p>Para isso, a primeira coisa que ele precisa é ser treinado.</p>
  <p>Ele precisa de um arquivo csv com duas colunas, uma com o nome "text" e a segunda com nome "category".</p>
  <p>Caso não tenha um arquivo com essas especificações, pode usar .</p>

  <div class="alert alert-warning" role="alert">
    Caso não tenha um arquivo com essas especificações, pode baixar   <%= link_to 'nesse link', download_path , target: "_blank", class: "alert-link" %> que foi feito pela BBC.
  </div>

  <p>Agora é simples, só importar ele para fazer o treinamento.</p>
  <%= form_tag({:action => :import}, multipart: true) do %>
    <%= file_field_tag :file, :accept => "text/csv" %>
    <%= submit_tag( "Importar CSV", class: "btn btn-dark") %>
  <% end %>

  <% if @categories.length >= 1 %>
  <div class="alert alert-success" role="alert">
    O treinamento foi um sucesso.
  </div>
    <h4>Suas categorias são: </h4>
    <% @categories.each do |category| %>
      <p><%= category %></p>
    <% end %>

    Agora é só colocar um texto para ser classificada.
    <div class="alert alert-dark" role="alert">
      Caso precise de uma notícia para testar, temos essa (desculpe se demorar ou estiver indisponivel, estamos usando uma api publica):
      <b><%= @news %></b>
    </div>
    <%= form_tag({:action => :classify}, multipart: true) do %>
      <%= text_area_tag :text %>
      <%= submit_tag( "Classificar", class: "btn btn-dark") %>
    <% end %>
  <% end %>


  <% if !@class_text.nil? && @class_text.length > 1 %>
    <div class="alert alert-success" role="alert">
    <%= @class_text %>
    </div>
  <% end %>

  <br>
  <br>
  <br>
</di>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsmachine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>